In [51]:
import numpy as np

new = np.loadtxt("abundances_new_massfrac_scaleothers_fac2.txt")
old = np.loadtxt("abundances.txt")

In [52]:
def rescale(array_to_scale, old_array, new_array, orig_index, new_index):
    old_array[np.where(old_array==0)] = 1.
    scale_factor = new_array[:, orig_index] / old_array[:, orig_index]
    scale_factor[np.where(np.isnan(scale_factor) == True)] = 1
    array_to_scale[:, new_index] = array_to_scale[:, new_index] * scale_factor
    return array_to_scale

In [53]:
header = np.genfromtxt('model.txt', max_rows=3)
model = np.genfromtxt("model.txt", skip_header=3).reshape(1000000, 10)
model[:,5]=np.sum(new[:,20:],1)
#model = rescale(model, old, new, 30, 4)
model = rescale(model, old, new, 28, 6)
model = rescale(model, old, new, 27, 7)
model = rescale(model, old, new, 26, 8)
model = rescale(model, old, new, 24, 9)

In [54]:
with open('model_scaleothers_fac2.txt', 'w') as f:
    f.write("%d \n" % (header[0]))
    f.write("%16.8e \n" % (header[1]))
    f.write("%16.8e \n" % (header[2]))
    for line in model:
        f.write("%d %16.8e %16.8e %16.8e %16.8e \n %16.8e %16.8e %16.8e %16.8e %16.8e \n" % (line[0], line[1], line[2], line[3], line[4], line[5], line[6], line[7], line[8], line[9]))

In [ ]:
# f = open('model_scaleothers_fac2.txt', 'a')
# f.write("%d \n" % (header[0]))
# f.write("%16.8e \n" % (header[1]))
# f.write("%16.8e \n" % (header[2]))
# f.close()
# np.savetxt(f, model, fmt="%d %16.8e %16.8e %16.8e %16.8e \n %16.8e %16.8e %16.8e %16.8e %16.8e")

In [44]:
np.sum(model[:,8])

0.1547309149593563

In [20]:
model.shape

(1000000, 10)

In [21]:
np.sum(old[:,24])

633092.2476675913

In [22]:
np.sum(new[:,24])

0.19341364368964584

In [23]:
print(old[:,24])

[1. 1. 1. ... 1. 1. 1.]


In [24]:
print(new[:,24])

[0. 0. 0. ... 0. 0. 0.]


In [30]:
model_old = np.genfromtxt("model.txt", skip_header=3).reshape(1000000, 10)

In [50]:
print(np.sum(model_old[:,9]),np.sum(model[:,9]))

0.24766759134947106 0.19341364368964584


In [39]:
model_old[:,4]

array([6.04714128e-17, 6.04714128e-17, 6.04714128e-17, ...,
       6.04714128e-17, 6.04714128e-17, 6.04714128e-17])

In [41]:
np.shape(model_old)

(1000000, 10)